@projectId = 2
@suggestionId = 2

### 機能提案の追加
POST http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "機能提案機能",
  "description": ""
}

### 機能提案の一覧
GET http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions
Authorization: Bearer {{token}}

### 機能提案の詳細
GET http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions/{{suggestionId}}
Authorization: Bearer {{token}}

### 機能提案の更新
PUT http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions/{{suggestionId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "機能提案機能",
  "description": "",
  "status": false
}


### 機能提案の削除
DELETE http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions/{{suggestionId}}
Authorization: Bearer {{token}}

### 機能提案コメントの追加
POST http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions/{{suggestionId}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "こんにちは"
}

### 機能提案コメントの一覧
GET http://localhost:3001/api/v1/projects/{{projectId}}/feature-suggestions/{{suggestionId}}/comments
Authorization: Bearer {{token}}
